apiVersion: "apps/v1"
kind: Deployment
metadata: 
  name: hello-world-service
spec: 
  replicas: 3
  selector:
    matchLabels:
      app: hello-world-service

  template:
    metadata:
      labels:
        app: hello-world-service
    spec:
      containers:
      - name: hello-world-service
        image: "lagom-hello-world-k8s-impl:7-7abed733-20190822-0954"
        env:
          - name: JAVA_OPTS
            value: "-Xms256m -Xmx256m -Dconfig.resource=prod-application.conf"
          - name: APPLICATION_SECRET
            valueFrom:
              secretKeyRef:
                name: hello-world-service-secret
                key: secret
          - name: POSTGRESQL_URL
            value: "jdbc:postgresql://postgres-service/postgres"
          - name: POSTGRESQL_USERNAME
            valueFrom:
              secretKeyRef:
                name: postgres-credentials
                key: user
          - name: POSTGRESQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: postgres-credentials
                key: password
          - name: KAFKA_SERVICE_NAME
            value: "_clients._tcp.strimzi-kafka-brokers"
          - name: REQUIRED_CONTACT_POINT_NR
            value: "3"
        ports:
          - name: management
            containerPort: 8558
        readinessProbe:
          httpGet:
            path: "/ready"
            port: management
          periodSeconds: 10
          failureThreshold: 10
          initialDelaySeconds: 20
        livenessProbe:
          httpGet:
            path: "/alive"
            port: management
          periodSeconds: 10
          failureThreshold: 10
          initialDelaySeconds: 20
        
        resources:
          limits: 
            memory: 512Mi
          requests:
            cpu: 0.25
            memory: 512Mi
            
---
apiVersion: v1
kind: Service
metadata:
  name: hello-world-service
spec: 
  ports:
    - name: http
      port: 80
      targetPort: 9000
  selector: 
    app: hello-world-service
  type: LoadBalancer
