name: "Deploy application to k8s"

on:
  push:
    branches:
      - master
      - pr-deployer

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_DEFAULT_REGION: us-east-1
  AWS_EKS_ClUSTER_NAME: dev

jobs:
  setup:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Get Short SHA
        id: get_sha
        run: echo ::set-output name=SHA_SHORT::$(git rev-parse --short HEAD)
      - uses: olafurpg/setup-scala@v11
      - name: Login to docker
        uses: docker/login-action@v1.12.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Install and configure aws
        run: |
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          unzip awscliv2.zip
          sudo ./aws/install
          aws configure
          aws eks update-kubeconfig --name $AWS_EKS_CLUSTER_NAME
      - name: Build and push image
        run: |
          sbt clean
          sbt clean docker:publish -Dversion:${{ steps.get_sha.outputs.SHA_SHORT }}
