name: "Deploy application to k8s"

on:
  push:
    branches:
      - master
      - pr-deployer

# env:
#   AWS_ACCESS_KEY_ID: ${ secrets.AWS_ACCESS_KEY_ID }
#   AWS_SECRET_ACCESS_KEY: ${ secrets.AWS_SECRET_ACCESS_KEY }
#   AWS_DEFAULT_REGION: ${ secrets.AWS_DEFAULT_REGION }
#   AWS_EKS_ClUSTER_NAME: dev
#   POSTGRES_USERNAME: ${ secrets.POSTGRES_USERNAME }
#   POSTGRES_PASSWORD: ${ secrets.POSTGRES_PASSWORD }

jobs:
  setup:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: olafurpg/setup-scala@v11
      - name: Login to docker
        uses: docker/login-action@v1.12.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Build and push image
        run: |
          sbt docker:stage
          sbt docker:publishLocal
          docker image ls
          sbt docker:publish
      # - name: Install and configure aws
      #   run: |
      #     curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
      #     unzip awscliv2.zip
      #     sudo ./aws/install
      #     aws configure
      #     aws eks update-kubeconfig --name $AWS_EKS_CLUSTER_NAME
      # - name: Install kubectl
      #   run: |
      #     curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
      #     sudo install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl
